spring:
  config:
    import:
      - optional:file:config/infura.yml
  application:
    name: data_producer
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC
    username: admin
    password: qwer1234
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
      password:


logging:
  file:
    path: logs
  level:
    root: INFO
    web: INFO
    '[com.crossangle]': INFO
  charset:
    console: UTF-8
    file: UTF-8