### {post} ETH 보유량
POST {{apiAddress}}/v1/ethereum/mainnet/accounts/tokens/transactions
Content-Type: application/json;charset=UTF-8

{
  "account": "0x39da41747a83aee658334415666f3ef92dd0d541",
  "tokenAddress": "ETH",
  "date": "20241221"
}

### {post} ERC20 보유량
POST {{apiAddress}}/v1/ethereum/mainnet/accounts/tokens/transactions
Content-Type: application/json;charset=UTF-8

{
  "account": "0x1bf621aa9cee3f6154881c25041bb39aed4ca7cc",
  "tokenAddress": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
  "date": "20241221"
}
