### {post} ETH 보유량
POST {{apiAddress}}/v1/ethereum/mainnet/accounts/tokens/transactions
Content-Type: application/json;charset=UTF-8

{
  "account": "0x0e423605a719C02078F0E30e97303349bEf7540c",
  "tokenAddress": "ETH",
  "date": "20241220"
}

### {post} ERC20 보유량
POST {{apiAddress}}/v1/ethereum/mainnet/accounts/tokens/transactions
Content-Type: application/json;charset=UTF-8

{
  "account": "0xdf5917540206f808Ee07deA6218fDeF0869A97AE",
  "tokenAddress": "0x13E4b8CfFe704d3De6F19E52b201d92c21EC18bD",
  "date": "20241220"
}
